            - name: sync gitee codebase
  # You may pin to the exact commit or the version.
  # uses: fretelli/sync-gitee-action@53b6761c6df2fc937f0ca1d8f1480483
  uses: fretelli/sync-gitee-action@v1
  with:
    # 用户名
    username:fretelli 
    # 密码
    password: f1989318
    # 仓库名
    repository: Dissilent网站
           
